[package]
name = "dylib-mitm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
mitm_macro = { path = "mitm-macro" }

[workspace]
members = [
    "mitm-macro",
]
